# Generated by Django 5.2.12 on 2026-09-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wharehouses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='address',
        ),
    ]
