# Generated by Django 5.2.12 on 2026-03-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('umb', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa')], default='UN', max_length=2)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('1', 'Insumo'), ('2', 'Matéria Prima'), ('3', 'Embalagem'), ('4', 'Material Acabado')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
